query propertyNames {
  propertyNames {
    propertyId
    propertyName
  }
}
mutation addPropertyName($input: String!){
  addPropertyName(propertyName: $input) {
    propertyId,
    propertyName
  }
}

mutation deletePropertyName($input: ID!){
  deletePropertyName(propertyId: $input) {
    propertyId,
    propertyName
  }
}

