query propertyNames {
  propertyNames {
    propertyId
    propertyName
  }
}
mutation addName($propertyName: String!){
  addPropertyName(propertyName: $propertyName) {
    success
    message
  }
}

mutation deleteName($propertyId: ID!){
  deletePropertyName(propertyId: $propertyId) {
    success
    message
  }
}

