query propertyValues($propertyId: ID!) {
  propertyValues(propertyId: $propertyId) {
    propertyId
    propertyValue
    propertyValueId
  }
}

mutation addValue($propertyId: ID!, $propertyValue: String!){
  addPropertyValue(propertyId: $propertyId, propertyValue: $propertyValue) {
    success
    message
  }
}

mutation deleteValue($propertyId: ID!, $propertyValueId: ID!){
  deletePropertyValue(propertyId: $propertyId, propertyValueId: $propertyValueId) {
    success
    message
  }
}